# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.vcbart_cs_adapt_split <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, rho_eps, a, b, N_u, rho_alpha, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob) {
    .Call('_VCBART_vcbart_cs_adapt_split', PACKAGE = 'VCBART', Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, rho_eps, a, b, N_u, rho_alpha, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob)
}

.vcbart_cs_fixed_split <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, rho_eps, theta_list, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob) {
    .Call('_VCBART_vcbart_cs_fixed_split', PACKAGE = 'VCBART', Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, rho_eps, theta_list, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob)
}

.vcbart_ind_adapt_split <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, a, b, N_u, rho_alpha, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob) {
    .Call('_VCBART_vcbart_ind_adapt_split', PACKAGE = 'VCBART', Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, a, b, N_u, rho_alpha, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob)
}

.vcbart_ind_fixed_split <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, theta_list, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob) {
    .Call('_VCBART_vcbart_ind_fixed_split', PACKAGE = 'VCBART', Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, M, ht_sigma_y, ht_tau, burn, nd, verbose, print_every, theta_list, tau_vec, alpha_vec, beta_vec, sigma_hat, nu_sigma, nu_tau, variance_prob)
}

