# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vc_BART_ar <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn = 1000L, nd = 1000L, rho = 0.9, sigma_hat = 1.0, m = 50L, ht_sigma_y = TRUE, ht_sigma_mu = FALSE, nu_sigma = 7, nu_sigma_mu = 7, variance_prob = 0.9, verbose = FALSE, print_every = 500L) {
    .Call(`_VCBART_vc_BART_ar`, Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn, nd, rho, sigma_hat, m, ht_sigma_y, ht_sigma_mu, nu_sigma, nu_sigma_mu, variance_prob, verbose, print_every)
}

vc_BART_cs <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn = 1000L, nd = 1000L, rho = 0.9, sigma_hat = 1.0, m = 50L, ht_sigma_y = TRUE, ht_sigma_mu = FALSE, nu_sigma = 7, nu_sigma_mu = 7, variance_prob = 0.9, verbose = FALSE, print_every = 500L) {
    .Call(`_VCBART_vc_BART_cs`, Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn, nd, rho, sigma_hat, m, ht_sigma_y, ht_sigma_mu, nu_sigma, nu_sigma_mu, variance_prob, verbose, print_every)
}

vc_BART_ind <- function(Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn = 1000L, nd = 1000L, sigma_hat = 1.0, m = 50L, ht_sigma_y = TRUE, ht_sigma_mu = FALSE, nu_sigma = 7, nu_sigma_mu = 7, variance_prob = 0.9, verbose = FALSE, print_every = 500L) {
    .Call(`_VCBART_vc_BART_ind`, Y, X_train, Z_train, n_vec_train, start_index_vec_train, X_test, Z_test, n_vec_test, start_index_vec_test, xinfo_list, sigma_mu_vec, alpha_vec, beta_vec, burn, nd, sigma_hat, m, ht_sigma_y, ht_sigma_mu, nu_sigma, nu_sigma_mu, variance_prob, verbose, print_every)
}

