# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.predict_vcbart <- function(tree_draws, p, M, tZ_cont, tZ_cat, verbose = TRUE) {
    .Call('_VCBART_predict_vcbart', PACKAGE = 'VCBART', tree_draws, p, M, tZ_cont, tZ_cat, verbose)
}

rescale_beta_mean <- function(beta_input, y_mean, y_sd, x_mean, x_sd) {
    .Call('_VCBART_rescale_beta_mean', PACKAGE = 'VCBART', beta_input, y_mean, y_sd, x_mean, x_sd)
}

rescale_beta <- function(beta_input, y_mean, y_sd, x_mean, x_sd) {
    .Call('_VCBART_rescale_beta', PACKAGE = 'VCBART', beta_input, y_mean, y_sd, x_mean, x_sd)
}

.vcbart_cs_fit <- function(Y_train, rho_init, subj_id_train, ni_train, tX_train, tZ_cont_train, tZ_cat_train, tX_test, tZ_cont_test, tZ_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_VCBART_vcbart_cs_fit', PACKAGE = 'VCBART', Y_train, rho_init, subj_id_train, ni_train, tX_train, tZ_cont_train, tZ_cat_train, tX_test, tZ_cont_test, tZ_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

.vcbart_ind_fit <- function(Y_train, subj_id_train, ni_train, tX_train, tZ_cont_train, tZ_cat_train, tX_test, tZ_cont_test, tZ_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_VCBART_vcbart_ind_fit', PACKAGE = 'VCBART', Y_train, subj_id_train, ni_train, tX_train, tZ_cont_train, tZ_cat_train, tX_test, tZ_cont_test, tZ_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, rc_split, prob_rc, a_rc, b_rc, sparse, a_u, b_u, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

